// <auto-generated />
using System;
using LogisticCompany.Db;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace LogisticCompany.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260517105359_AddUserFields")]
    partial class AddUserFields
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .UseCollation("utf8mb4_0900_ai_ci")
                .HasAnnotation("ProductVersion", "9.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.HasCharSet(modelBuilder, "utf8mb4");
            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("Branch", b =>
                {
                    b.Property<int>("BranchesId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("branches_ID");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("BranchesId"));

                    b.Property<string>("AddressBranches")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("address_branches")
                        .UseCollation("utf8mb3_general_ci");

                    MySqlPropertyBuilderExtensions.HasCharSet(b.Property<string>("AddressBranches"), "utf8mb3");

                    b.Property<string>("NameBranches")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("name_branches")
                        .UseCollation("utf8mb3_general_ci");

                    MySqlPropertyBuilderExtensions.HasCharSet(b.Property<string>("NameBranches"), "utf8mb3");

                    b.Property<string>("PhoneBranches")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("phone_branches")
                        .UseCollation("utf8mb3_general_ci");

                    MySqlPropertyBuilderExtensions.HasCharSet(b.Property<string>("PhoneBranches"), "utf8mb3");

                    b.Property<int?>("TownId")
                        .HasColumnType("int")
                        .HasColumnName("town_ID");

                    b.HasKey("BranchesId")
                        .HasName("PRIMARY");

                    b.HasIndex(new[] { "TownId" }, "FK_branches_town");

                    b.ToTable("branches", (string)null);
                });

            modelBuilder.Entity("Client", b =>
                {
                    b.Property<int>("ClientsId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("clients_ID");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("ClientsId"));

                    b.Property<int>("ClientTypeId")
                        .HasColumnType("int")
                        .HasColumnName("client_type_id");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("email")
                        .UseCollation("utf8mb3_general_ci");

                    MySqlPropertyBuilderExtensions.HasCharSet(b.Property<string>("Email"), "utf8mb3");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("phone")
                        .UseCollation("utf8mb3_general_ci");

                    MySqlPropertyBuilderExtensions.HasCharSet(b.Property<string>("Phone"), "utf8mb3");

                    b.Property<int?>("UserId")
                        .HasColumnType("int");

                    b.HasKey("ClientsId")
                        .HasName("PRIMARY");

                    b.HasIndex("UserId");

                    b.HasIndex(new[] { "ClientTypeId" }, "client_type_id");

                    b.ToTable("clients", (string)null);
                });

            modelBuilder.Entity("ClientType", b =>
                {
                    b.Property<int>("ClientTypeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("client_type_id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("ClientTypeId"));

                    b.Property<string>("TypeName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("type_name");

                    b.HasKey("ClientTypeId")
                        .HasName("PRIMARY");

                    b.HasIndex(new[] { "TypeName" }, "type_name")
                        .IsUnique();

                    b.ToTable("client_types", (string)null);
                });

            modelBuilder.Entity("CompanyClient", b =>
                {
                    b.Property<int>("CompanyId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("company_ID");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("CompanyId"));

                    b.Property<int>("ClientsId")
                        .HasColumnType("int")
                        .HasColumnName("clients_ID");

                    b.Property<string>("CompanyName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("company_name")
                        .UseCollation("utf8mb3_general_ci");

                    MySqlPropertyBuilderExtensions.HasCharSet(b.Property<string>("CompanyName"), "utf8mb3");

                    b.Property<string>("Inn")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("INN")
                        .UseCollation("utf8mb3_general_ci");

                    MySqlPropertyBuilderExtensions.HasCharSet(b.Property<string>("Inn"), "utf8mb3");

                    b.HasKey("CompanyId")
                        .HasName("PRIMARY");

                    b.HasIndex(new[] { "ClientsId" }, "FK_company_clients_clients");

                    b.ToTable("company_clients", (string)null);
                });

            modelBuilder.Entity("DeliveryType", b =>
                {
                    b.Property<int>("DeliveryTypeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("delivery_type_ID");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("DeliveryTypeId"));

                    b.Property<string>("NameDeliveryType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("name_delivery_type")
                        .UseCollation("utf8mb3_general_ci");

                    MySqlPropertyBuilderExtensions.HasCharSet(b.Property<string>("NameDeliveryType"), "utf8mb3");

                    b.HasKey("DeliveryTypeId")
                        .HasName("PRIMARY");

                    b.ToTable("delivery_type", (string)null);
                });

            modelBuilder.Entity("IndividualClient", b =>
                {
                    b.Property<int>("IndividualId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("individual_ID");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("IndividualId"));

                    b.Property<int>("ClientsId")
                        .HasColumnType("int")
                        .HasColumnName("clients_ID");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("first_name")
                        .UseCollation("utf8mb3_general_ci");

                    MySqlPropertyBuilderExtensions.HasCharSet(b.Property<string>("FirstName"), "utf8mb3");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("last_name")
                        .UseCollation("utf8mb3_general_ci");

                    MySqlPropertyBuilderExtensions.HasCharSet(b.Property<string>("LastName"), "utf8mb3");

                    b.Property<DateOnly?>("PassportDateOfIssue")
                        .HasColumnType("date")
                        .HasColumnName("passport_date_of_issue");

                    b.Property<string>("PassportNumber")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("passport_number")
                        .UseCollation("utf8mb3_general_ci");

                    MySqlPropertyBuilderExtensions.HasCharSet(b.Property<string>("PassportNumber"), "utf8mb3");

                    b.Property<string>("PatronymicName")
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("patronymic_name")
                        .UseCollation("utf8mb3_general_ci");

                    MySqlPropertyBuilderExtensions.HasCharSet(b.Property<string>("PatronymicName"), "utf8mb3");

                    b.HasKey("IndividualId")
                        .HasName("PRIMARY");

                    b.HasIndex(new[] { "ClientsId" }, "FK_individual_clients_clients");

                    b.ToTable("individual_clients", (string)null);
                });

            modelBuilder.Entity("LogisticCompany.Domain.Entities.Employee.Employee", b =>
                {
                    b.Property<int>("EmployeeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("EmployeeId"));

                    b.Property<int>("BranchId")
                        .HasColumnType("int");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("PatronymicName")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)");

                    b.Property<string>("Position")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<int?>("UserId")
                        .HasColumnType("int");

                    b.HasKey("EmployeeId");

                    b.HasIndex("BranchId");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("Phone")
                        .IsUnique();

                    b.HasIndex("UserId");

                    b.ToTable("Employees");
                });

            modelBuilder.Entity("LogisticCompany.Domain.Entities.Location.Country", b =>
                {
                    b.Property<int>("CountryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("country_ID");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("CountryId"));

                    b.Property<string>("CountryName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("country_name")
                        .UseCollation("utf8mb3_general_ci");

                    MySqlPropertyBuilderExtensions.HasCharSet(b.Property<string>("CountryName"), "utf8mb3");

                    b.HasKey("CountryId")
                        .HasName("PRIMARY");

                    b.ToTable("country", (string)null);
                });

            modelBuilder.Entity("LogisticCompany.Domain.Entities.Location.Town", b =>
                {
                    b.Property<int>("TownId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("town_ID");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("TownId"));

                    b.Property<int>("CountryId")
                        .HasColumnType("int")
                        .HasColumnName("country_ID");

                    b.Property<string>("TownName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("town_name")
                        .UseCollation("utf8mb3_general_ci");

                    MySqlPropertyBuilderExtensions.HasCharSet(b.Property<string>("TownName"), "utf8mb3");

                    b.HasKey("TownId")
                        .HasName("PRIMARY");

                    b.HasIndex(new[] { "CountryId" }, "FK_town_country");

                    b.ToTable("town", (string)null);
                });

            modelBuilder.Entity("LogisticCompany.Domain.Entities.Orders.DeliveryTariff", b =>
                {
                    b.Property<int>("TariffId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("TariffId"));

                    b.Property<decimal>("BasePrice")
                        .HasColumnType("decimal(65,30)");

                    b.Property<int>("DeliveryTypeId")
                        .HasColumnType("int");

                    b.Property<bool>("IsActive")
                        .HasColumnType("tinyint(1)");

                    b.Property<decimal>("PricePerKg")
                        .HasColumnType("decimal(65,30)");

                    b.Property<decimal>("PricePerKm")
                        .HasColumnType("decimal(65,30)");

                    b.Property<int>("TransportTypeId")
                        .HasColumnType("int");

                    b.HasKey("TariffId")
                        .HasName("PRIMARY");

                    b.ToTable("DeliveryTariffs");
                });

            modelBuilder.Entity("LogisticCompany.Domain.Entities.Orders.ParcelTemplate", b =>
                {
                    b.Property<int>("TemplateId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("template_id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("TemplateId"));

                    b.Property<int?>("HeightCm")
                        .HasColumnType("int")
                        .HasColumnName("height_cm");

                    b.Property<int?>("LengthCm")
                        .HasColumnType("int")
                        .HasColumnName("length_cm");

                    b.Property<int?>("MaxWeight")
                        .HasColumnType("int")
                        .HasColumnName("max_weight");

                    b.Property<string>("TemplateName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("template_name")
                        .UseCollation("utf8mb3_general_ci");

                    MySqlPropertyBuilderExtensions.HasCharSet(b.Property<string>("TemplateName"), "utf8mb3");

                    b.Property<int?>("WidthCm")
                        .HasColumnType("int")
                        .HasColumnName("width_cm");

                    b.HasKey("TemplateId")
                        .HasName("PRIMARY");

                    b.ToTable("parcel_templates", (string)null);
                });

            modelBuilder.Entity("LogisticCompany.Domain.Entities.Orders.Payment", b =>
                {
                    b.Property<int>("PaymentsId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("payments_ID");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("PaymentsId"));

                    b.Property<string>("Amount")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("varchar(80)")
                        .HasColumnName("amount");

                    b.Property<int>("OrdersId")
                        .HasColumnType("int")
                        .HasColumnName("orders_ID");

                    b.Property<DateTime?>("PaymentDate")
                        .HasColumnType("datetime")
                        .HasColumnName("payment_date");

                    b.Property<int>("PaymentMethodId")
                        .HasColumnType("int")
                        .HasColumnName("payment_method_ID");

                    b.HasKey("PaymentsId")
                        .HasName("PRIMARY");

                    b.HasIndex(new[] { "PaymentMethodId" }, "FK_payments_method");

                    b.HasIndex(new[] { "OrdersId" }, "FK_payments_orders");

                    b.ToTable("payments", (string)null);
                });

            modelBuilder.Entity("LogisticCompany.Domain.Entities.Orders.PaymentMethod", b =>
                {
                    b.Property<int>("PaymentMethodId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("payment_method_ID");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("PaymentMethodId"));

                    b.Property<string>("MethodName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("method_name")
                        .UseCollation("utf8mb3_general_ci");

                    MySqlPropertyBuilderExtensions.HasCharSet(b.Property<string>("MethodName"), "utf8mb3");

                    b.HasKey("PaymentMethodId")
                        .HasName("PRIMARY");

                    b.ToTable("payment_methods", (string)null);
                });

            modelBuilder.Entity("LogisticCompany.Domain.Entities.Orders.TransportType", b =>
                {
                    b.Property<int>("TransportTypeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("transport_type_ID");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("TransportTypeId"));

                    b.Property<string>("NameTransportType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("name_transport_type")
                        .UseCollation("utf8mb3_general_ci");

                    MySqlPropertyBuilderExtensions.HasCharSet(b.Property<string>("NameTransportType"), "utf8mb3");

                    b.HasKey("TransportTypeId")
                        .HasName("PRIMARY");

                    b.ToTable("transport_type", (string)null);
                });

            modelBuilder.Entity("LogisticCompany.Domain.Entities.Tracking.Tracking", b =>
                {
                    b.Property<int>("TrackingsId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("trackings_ID");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("TrackingsId"));

                    b.Property<int?>("BranchesId")
                        .HasColumnType("int")
                        .HasColumnName("branches_ID");

                    b.Property<string>("LocationTrackings")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("location_trackings")
                        .UseCollation("utf8mb3_general_ci");

                    MySqlPropertyBuilderExtensions.HasCharSet(b.Property<string>("LocationTrackings"), "utf8mb3");

                    b.Property<int>("OrdersId")
                        .HasColumnType("int")
                        .HasColumnName("orders_ID");

                    b.Property<int>("StatusId")
                        .HasColumnType("int")
                        .HasColumnName("status_ID");

                    b.Property<DateTime>("UpdateDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasColumnName("update_date")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.HasKey("TrackingsId")
                        .HasName("PRIMARY");

                    b.HasIndex(new[] { "BranchesId" }, "FK_trackings_branches");

                    b.HasIndex(new[] { "OrdersId" }, "FK_trackings_orders");

                    b.HasIndex(new[] { "StatusId" }, "FK_trackings_status");

                    b.ToTable("trackings", (string)null);
                });

            modelBuilder.Entity("Order", b =>
                {
                    b.Property<int>("OrdersId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("orders_ID");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("OrdersId"));

                    b.Property<decimal?>("CalculatedPrice")
                        .HasPrecision(10, 2)
                        .HasColumnType("decimal(10,2)")
                        .HasColumnName("calculate_price");

                    b.Property<int>("ClientsId")
                        .HasColumnType("int")
                        .HasColumnName("clients_ID");

                    b.Property<string>("CourierDestAddress")
                        .HasMaxLength(80)
                        .HasColumnType("varchar(80)")
                        .HasColumnName("courier_dest_address")
                        .UseCollation("utf8mb3_general_ci");

                    MySqlPropertyBuilderExtensions.HasCharSet(b.Property<string>("CourierDestAddress"), "utf8mb3");

                    b.Property<DateTime?>("CreatedDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasColumnName("create_Date")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<int?>("DeliveryTypeId")
                        .HasColumnType("int")
                        .HasColumnName("delivery_type_ID");

                    b.Property<string>("DescriptionParcel")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("description_parcel")
                        .UseCollation("utf8mb3_general_ci");

                    MySqlPropertyBuilderExtensions.HasCharSet(b.Property<string>("DescriptionParcel"), "utf8mb3");

                    b.Property<int>("DestinationBranchId")
                        .HasColumnType("int")
                        .HasColumnName("destination_branch_ID");

                    b.Property<int>("DestinationTownId")
                        .HasColumnType("int")
                        .HasColumnName("destination_town_ID");

                    b.Property<string>("FirstRecepientName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("first_recepient_name")
                        .UseCollation("utf8mb3_general_ci");

                    MySqlPropertyBuilderExtensions.HasCharSet(b.Property<string>("FirstRecepientName"), "utf8mb3");

                    b.Property<decimal?>("HeightCm")
                        .HasPrecision(10, 2)
                        .HasColumnType("decimal(10,2)")
                        .HasColumnName("height_cm");

                    b.Property<string>("LastRecepientName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("last_recepient_name")
                        .UseCollation("utf8mb3_general_ci");

                    MySqlPropertyBuilderExtensions.HasCharSet(b.Property<string>("LastRecepientName"), "utf8mb3");

                    b.Property<decimal?>("LengthCm")
                        .HasPrecision(10, 2)
                        .HasColumnType("decimal(10,2)")
                        .HasColumnName("length_cm");

                    b.Property<string>("MiddleRecepientName")
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("middle_recepient_name")
                        .UseCollation("utf8mb3_general_ci");

                    MySqlPropertyBuilderExtensions.HasCharSet(b.Property<string>("MiddleRecepientName"), "utf8mb3");

                    b.Property<string>("OrderNumber")
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("order_number");

                    b.Property<int>("OriginTownId")
                        .HasColumnType("int")
                        .HasColumnName("origin_town_ID");

                    b.Property<string>("PhoneRecepient")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("phone_recepient")
                        .UseCollation("utf8mb3_general_ci");

                    MySqlPropertyBuilderExtensions.HasCharSet(b.Property<string>("PhoneRecepient"), "utf8mb3");

                    b.Property<int>("PickupBranchesId")
                        .HasColumnType("int")
                        .HasColumnName("pickup_branches_ID");

                    b.Property<int?>("TemplateId")
                        .HasColumnType("int")
                        .HasColumnName("template_id");

                    b.Property<int>("TransportTypeId")
                        .HasColumnType("int")
                        .HasColumnName("transport_type_ID");

                    b.Property<decimal?>("Weight")
                        .HasPrecision(10, 2)
                        .HasColumnType("decimal(10,2)")
                        .HasColumnName("weight");

                    b.Property<decimal?>("WidthCm")
                        .HasPrecision(10, 2)
                        .HasColumnType("decimal(10,2)")
                        .HasColumnName("width_cm");

                    b.HasKey("OrdersId")
                        .HasName("PRIMARY");

                    b.HasIndex(new[] { "PickupBranchesId" }, "FK_orders_branches");

                    b.HasIndex(new[] { "ClientsId" }, "FK_orders_clients");

                    b.HasIndex(new[] { "DeliveryTypeId" }, "FK_orders_deliveryType");

                    b.HasIndex(new[] { "DestinationTownId" }, "FK_orders_destinationTown");

                    b.HasIndex(new[] { "OriginTownId" }, "FK_orders_originTown");

                    b.HasIndex(new[] { "TemplateId" }, "FK_orders_templates");

                    b.HasIndex(new[] { "TransportTypeId" }, "FK_orders_transportType");

                    b.ToTable("orders", (string)null);
                });

            modelBuilder.Entity("StatusDelivery", b =>
                {
                    b.Property<int>("StatusId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("status_ID");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("StatusId"));

                    b.Property<string>("StatusName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("status_name")
                        .UseCollation("utf8mb3_general_ci");

                    MySqlPropertyBuilderExtensions.HasCharSet(b.Property<string>("StatusName"), "utf8mb3");

                    b.HasKey("StatusId")
                        .HasName("PRIMARY");

                    b.ToTable("status_delivery", (string)null);
                });

            modelBuilder.Entity("User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<int>("FailedLoginAttempts")
                        .HasColumnType("int");

                    b.Property<bool>("IsTemporaryPassword")
                        .HasColumnType("tinyint(1)");

                    b.Property<DateTime?>("LastLoginAt")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime?>("LockoutEnd")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.Property<string>("Role")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("enum('Admin','User')")
                        .HasDefaultValueSql("'User'");

                    b.HasKey("Id")
                        .HasName("PRIMARY");

                    b.HasIndex(new[] { "Email" }, "Email")
                        .IsUnique();

                    b.ToTable("users", (string)null);
                });

            modelBuilder.Entity("Branch", b =>
                {
                    b.HasOne("LogisticCompany.Domain.Entities.Location.Town", "Town")
                        .WithMany("Branches")
                        .HasForeignKey("TownId")
                        .HasConstraintName("FK_branches_town");

                    b.Navigation("Town");
                });

            modelBuilder.Entity("Client", b =>
                {
                    b.HasOne("ClientType", "ClientType")
                        .WithMany("Clients")
                        .HasForeignKey("ClientTypeId")
                        .IsRequired()
                        .HasConstraintName("clients_ibfk_1");

                    b.HasOne("User", "User")
                        .WithMany("Clients")
                        .HasForeignKey("UserId");

                    b.Navigation("ClientType");

                    b.Navigation("User");
                });

            modelBuilder.Entity("CompanyClient", b =>
                {
                    b.HasOne("Client", "Clients")
                        .WithMany("CompanyClients")
                        .HasForeignKey("ClientsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_company_clients_clients");

                    b.Navigation("Clients");
                });

            modelBuilder.Entity("IndividualClient", b =>
                {
                    b.HasOne("Client", "Clients")
                        .WithMany("IndividualClients")
                        .HasForeignKey("ClientsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_individual_clients_clients");

                    b.Navigation("Clients");
                });

            modelBuilder.Entity("LogisticCompany.Domain.Entities.Employee.Employee", b =>
                {
                    b.HasOne("Branch", "Branch")
                        .WithMany("Employees")
                        .HasForeignKey("BranchId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Branch");

                    b.Navigation("User");
                });

            modelBuilder.Entity("LogisticCompany.Domain.Entities.Location.Town", b =>
                {
                    b.HasOne("LogisticCompany.Domain.Entities.Location.Country", "Country")
                        .WithMany("Towns")
                        .HasForeignKey("CountryId")
                        .IsRequired()
                        .HasConstraintName("FK_town_country");

                    b.Navigation("Country");
                });

            modelBuilder.Entity("LogisticCompany.Domain.Entities.Orders.Payment", b =>
                {
                    b.HasOne("Order", "Orders")
                        .WithMany("Payments")
                        .HasForeignKey("OrdersId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_payments_orders");

                    b.HasOne("LogisticCompany.Domain.Entities.Orders.PaymentMethod", "PaymentMethod")
                        .WithMany("Payments")
                        .HasForeignKey("PaymentMethodId")
                        .IsRequired()
                        .HasConstraintName("FK_payments_method");

                    b.Navigation("Orders");

                    b.Navigation("PaymentMethod");
                });

            modelBuilder.Entity("LogisticCompany.Domain.Entities.Tracking.Tracking", b =>
                {
                    b.HasOne("Branch", "Branches")
                        .WithMany("Trackings")
                        .HasForeignKey("BranchesId")
                        .HasConstraintName("FK_trackings_branches");

                    b.HasOne("Order", "Orders")
                        .WithMany("Trackings")
                        .HasForeignKey("OrdersId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_trackings_orders");

                    b.HasOne("StatusDelivery", "Status")
                        .WithMany("Trackings")
                        .HasForeignKey("StatusId")
                        .IsRequired()
                        .HasConstraintName("FK_trackings_status");

                    b.Navigation("Branches");

                    b.Navigation("Orders");

                    b.Navigation("Status");
                });

            modelBuilder.Entity("Order", b =>
                {
                    b.HasOne("Client", "Clients")
                        .WithMany("Orders")
                        .HasForeignKey("ClientsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_orders_clients");

                    b.HasOne("DeliveryType", "DeliveryType")
                        .WithMany("Orders")
                        .HasForeignKey("DeliveryTypeId")
                        .HasConstraintName("FK_orders_deliveryType");

                    b.HasOne("LogisticCompany.Domain.Entities.Location.Town", "DestinationTown")
                        .WithMany("OrderDestinationTowns")
                        .HasForeignKey("DestinationTownId")
                        .IsRequired()
                        .HasConstraintName("FK_orders_destinationTown");

                    b.HasOne("LogisticCompany.Domain.Entities.Location.Town", "OriginTown")
                        .WithMany("OrderOriginTowns")
                        .HasForeignKey("OriginTownId")
                        .IsRequired()
                        .HasConstraintName("FK_orders_originTown");

                    b.HasOne("Branch", "PickupBranches")
                        .WithMany("Orders")
                        .HasForeignKey("PickupBranchesId")
                        .IsRequired()
                        .HasConstraintName("FK_orders_branches");

                    b.HasOne("LogisticCompany.Domain.Entities.Orders.ParcelTemplate", "Template")
                        .WithMany("Orders")
                        .HasForeignKey("TemplateId")
                        .HasConstraintName("FK_orders_templates");

                    b.HasOne("LogisticCompany.Domain.Entities.Orders.TransportType", "TransportType")
                        .WithMany("Orders")
                        .HasForeignKey("TransportTypeId")
                        .IsRequired()
                        .HasConstraintName("FK_orders_transportType");

                    b.Navigation("Clients");

                    b.Navigation("DeliveryType");

                    b.Navigation("DestinationTown");

                    b.Navigation("OriginTown");

                    b.Navigation("PickupBranches");

                    b.Navigation("Template");

                    b.Navigation("TransportType");
                });

            modelBuilder.Entity("Branch", b =>
                {
                    b.Navigation("Employees");

                    b.Navigation("Orders");

                    b.Navigation("Trackings");
                });

            modelBuilder.Entity("Client", b =>
                {
                    b.Navigation("CompanyClients");

                    b.Navigation("IndividualClients");

                    b.Navigation("Orders");
                });

            modelBuilder.Entity("ClientType", b =>
                {
                    b.Navigation("Clients");
                });

            modelBuilder.Entity("DeliveryType", b =>
                {
                    b.Navigation("Orders");
                });

            modelBuilder.Entity("LogisticCompany.Domain.Entities.Location.Country", b =>
                {
                    b.Navigation("Towns");
                });

            modelBuilder.Entity("LogisticCompany.Domain.Entities.Location.Town", b =>
                {
                    b.Navigation("Branches");

                    b.Navigation("OrderDestinationTowns");

                    b.Navigation("OrderOriginTowns");
                });

            modelBuilder.Entity("LogisticCompany.Domain.Entities.Orders.ParcelTemplate", b =>
                {
                    b.Navigation("Orders");
                });

            modelBuilder.Entity("LogisticCompany.Domain.Entities.Orders.PaymentMethod", b =>
                {
                    b.Navigation("Payments");
                });

            modelBuilder.Entity("LogisticCompany.Domain.Entities.Orders.TransportType", b =>
                {
                    b.Navigation("Orders");
                });

            modelBuilder.Entity("Order", b =>
                {
                    b.Navigation("Payments");

                    b.Navigation("Trackings");
                });

            modelBuilder.Entity("StatusDelivery", b =>
                {
                    b.Navigation("Trackings");
                });

            modelBuilder.Entity("User", b =>
                {
                    b.Navigation("Clients");
                });
#pragma warning restore 612, 618
        }
    }
}
